FROM ruby:2.6.5
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    default-mysql-client \
    nodejs \
    npm \
    vim \
    sudo && \
    npm install -g -y yarn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app
ADD ./Gemfile Gemfile
ADD ./Gemfile.lock Gemfile.lock
RUN gem install bundler
RUN bundle install
ADD . /app
# RUN mkdir -p tmp/sockets

# RUN SECRET_KEY_BASE=placeholder bundle exec rails assets:precompile \
#  && yarn cache clean \
#  && rm -rf node_modules tmp/cache

ENV RAILS_SERVE_STATIC_FILES="true"

# COPY entrypoint.sh /usr/bin/
# RUN chmod +x /usr/bin/entrypoint.sh
# ENTRYPOINT ["entrypoint.sh"]
# EXPOSE 3000
# 本番
CMD ["bundle", "exec", "puma", "-e", "production", "-C", "config/puma.rb"]
