FROM ruby:2.6.5
RUN apt-get update -y && \
    apt-get install --no-install-recommends -y \
    default-mysql-client \
    nodejs \
    npm \
    vim \
    sudo && \
    npm install -g -y yarn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app
ADD ./Gemfile Gemfile
ADD ./Gemfile.lock Gemfile.lock
RUN gem install bundler
RUN bundle install
ADD . /app

ENV RAILS_SERVE_STATIC_FILES="true"

CMD ["bundle", "exec", "puma", "-e", "production", "-C", "config/puma.rb"]
