version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      # - db-data:/tmp/mysql.sock
      # - db-data:/var/lib/mysql
    ports:
      - 3306
    cap_add:
      - SYS_NICE

  app:
    build:
      context: .
      dockerfile: ./containers/rails/Dockerfile_development
    env_file:
      - ./environments/db.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    tty: true
    stdin_open: true
  web:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - ./public:/app/public
      - ./tmp:/app/tmp
    ports:
      - "80:80"
    depends_on:
      - app
volumes:

  # db-data:

