version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
  db:
    image: mysql:latest
    env_file:
      - ./environments/db.env
    ports:
      - '3308:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/tmp/mysql.sock
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./tmp:/app/tmp
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: