version: '3'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: trello
    # env_file:
    #   - ./environments/db.env
    volumes:
      - db-data:/tmp/mysql.sock
      # - ./tmp/db:/var/lib/mysql/data
      # - ./mysql_data:/var/lib/mysql
      # - ./conf/my.cnf:/etc/my.cnf
    ports:
      - 3306
    cap_add:
      - SYS_NICE

  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
  web:
    build:
      context: .
      dockerfile: ./containers/nginx/Dockerfile
    volumes:
      - ./public:/app/public
      - ./tmp:/app/tmp
    ports:
      - "8080:80"
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
