default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: trello_development

test:
  <<: *default
  database: trello_test

production:
  <<: *default
  database: trello_production
  username: root
  socket: /var/lib/mysql/mysql.sock
  password: tttkr9564