default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: db

development:
  <<: *default
  database: trello_development
  # username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  # password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  # port: 3306
  # host: db

test:
  <<: *default
  database: trello_test
  # host: 127.0.0.1

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>