default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  # password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  # host: db
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: trello_development

test:
  <<: *default
  database: trello_test

production:
  <<: *default
  database: trello_production
  # socket: /var/lib/mysql/mysql.sock
  # host: <%= ENV['DB_HOST'] %>
  # database: <%= ENV['DB_DATABASE'] %>
  # username: <%= ENV['DB_USERNAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>
